# Generated by Django 5.1b1 on 2024-07-22 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
