# Generated by Django 5.1b1 on 2024-07-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='bids',
            new_name='usersWatching',
        ),
    ]
