# Generated by Django 5.1b1 on 2024-07-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bids_auctionlisting_userswatching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='usersWatching',
            new_name='watchers',
        ),
    ]
