# Generated by Django 5.1b1 on 2024-07-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='currentPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
